services:
  backend:
    build:
      context: ./backend  
    ports:
      - "8080:8080" 
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://localhost 
      - REDIS_HOST=redis  
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=exampledb
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend 
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api  
    networks:
      - app-network
  redis:
    image: redis:7  
    restart: unless-stopped  
    networks:
      - app-network
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exampledb
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
