services:
  backend:
    build:
      context: ./backend  
    ports:
      - "8080:8080" 
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://localhost:5000 
      - REDIS_HOST=redis  
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=exampledb
    depends_on:
      - redis
      - postgres
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend 
    ports:
      - "5000:5000"  
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080  
    networks:
      - app-network
  redis:
    image: redis:7  
    restart: unless-stopped  
    networks:
      - app-network
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exampledb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
