version: "3.9"
services:
  app:
    build:
      context: ./app
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=my_database
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
